# Generated by Django 4.0.4 on 2022-05-22 14:38

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('url', models.URLField()),
                ('original_image', models.URLField(validators=[django.core.validators.RegexValidator(message='Not a valid URL.', regex='/^(https?:\\/\\/)?([\\da-z\\.-]+)\\.([a-z\\.]{2,6})([\\/\\w \\.-]*)*\\/?$/')])),
                ('original_image_size', models.CharField(max_length=45)),
                ('small_image', models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Not a valid URL.', regex='/^(https?:\\/\\/)?([\\da-z\\.-]+)\\.([a-z\\.]{2,6})([\\/\\w \\.-]*)*\\/?$/')])),
                ('medium_image', models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Not a valid URL.', regex='/^(https?:\\/\\/)?([\\da-z\\.-]+)\\.([a-z\\.]{2,6})([\\/\\w \\.-]*)*\\/?$/')])),
                ('large_image', models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Not a valid URL.', regex='/^(https?:\\/\\/)?([\\da-z\\.-]+)\\.([a-z\\.]{2,6})([\\/\\w \\.-]*)*\\/?$/')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product_image',
            },
        ),
        migrations.AddIndex(
            model_name='productimages',
            index=models.Index(fields=['url'], name='product_ima_url_ab107c_idx'),
        ),
    ]
